### ISSUE TITLE
Nuget api key is present in bat file

### ISSUE THREAD

**Issue by SergeyFilippov** [baiyanzhao/FolderBrowserForWPF#2]
The API key for nuget is commited into repository inside of a batch file.
Using it anyone can push any code under the same name into nuget.org repository.

I'm talking about:
nuget.bat
https://github.com/baiyanzhao/FolderBrowserForWPF/blob/master/FolderBrowserForWPF/nuget.bat

**Comment by BaY1251** [comment]
Thank you!!  I delete is in new Version, and get a new API Key
